// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpy_trPO9MLOLYUUsk7iKt-paloMvh4AI',
    appId: '1:258194497859:web:c42862089507a745a14ff6',
    messagingSenderId: '258194497859',
    projectId: 'pv-monitoring-system-d1ade',
    authDomain: 'pv-monitoring-system-d1ade.firebaseapp.com',
    databaseURL: 'https://pv-monitoring-system-d1ade-default-rtdb.firebaseio.com',
    storageBucket: 'pv-monitoring-system-d1ade.firebasestorage.app',
    measurementId: 'G-DV5PBRPL3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI_o5Rd6XpcaWS8haMlzfurE9v8eLcAUo',
    appId: '1:258194497859:android:a111aaedefaf6790a14ff6',
    messagingSenderId: '258194497859',
    projectId: 'pv-monitoring-system-d1ade',
    databaseURL: 'https://pv-monitoring-system-d1ade-default-rtdb.firebaseio.com',
    storageBucket: 'pv-monitoring-system-d1ade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQgdnajUt0dWQnRyfQG5KlgUZ5YKp4Rs',
    appId: '1:258194497859:ios:1190efbad53a6cd5a14ff6',
    messagingSenderId: '258194497859',
    projectId: 'pv-monitoring-system-d1ade',
    databaseURL: 'https://pv-monitoring-system-d1ade-default-rtdb.firebaseio.com',
    storageBucket: 'pv-monitoring-system-d1ade.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdQgdnajUt0dWQnRyfQG5KlgUZ5YKp4Rs',
    appId: '1:258194497859:ios:1190efbad53a6cd5a14ff6',
    messagingSenderId: '258194497859',
    projectId: 'pv-monitoring-system-d1ade',
    databaseURL: 'https://pv-monitoring-system-d1ade-default-rtdb.firebaseio.com',
    storageBucket: 'pv-monitoring-system-d1ade.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpy_trPO9MLOLYUUsk7iKt-paloMvh4AI',
    appId: '1:258194497859:web:271e84bed117ec53a14ff6',
    messagingSenderId: '258194497859',
    projectId: 'pv-monitoring-system-d1ade',
    authDomain: 'pv-monitoring-system-d1ade.firebaseapp.com',
    databaseURL: 'https://pv-monitoring-system-d1ade-default-rtdb.firebaseio.com',
    storageBucket: 'pv-monitoring-system-d1ade.firebasestorage.app',
    measurementId: 'G-K95D81SMJ4',
  );

}